# Generated by Django 3.2 on 2021-04-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='need_to_pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
